export const DASH_COPY = {
  en: {
    nav: {
      overview: "Overview",
      shipments: "Shipments",
      fleet: "Fleet",
      drivers: "Drivers",
      tracking: "Tracking",
      payments: "Payments",
      reports: "Reports",
      settings: "Settings",
      logout: "Sign out",
    },
    profile: {
      name: "Amani Mwakalinga",
      email: "amani@highwaycargo.co.tz",
      settings: "Account settings",
      logout: "Sign out",
    },
    overview: {
      greeting: "Good to see you, Amani.",
      sub: "Here's what's moving across your fleet today.",
    },
    stats: {
      shipments: "Active shipments",
      trucks: "Trucks on the road",
      revenue: "Revenue this month",
      onTime: "On-time rate",
    },
    table: {
      title: "Recent shipments",
      viewAll: "View all",
      code: "Code",
      route: "Route",
      truck: "Truck & driver",
      status: "Status",
      eta: "ETA",
      status_transit: "In transit",
      status_delivered: "Delivered",
      status_delayed: "Delayed",
      status_loading: "Loading",
    },
    map: {
      title: "Live fleet",
      active: "active routes",
    },
    trust: {
      eyebrow: "Why fleets trust CourierFlow",
      items: [
        { stat: "256-bit", label: "Encrypted mobile money payments" },
        { stat: "97%", label: "On-time delivery rate" },
        { stat: "180+", label: "Fleets across Tanzania" },
        { stat: "24/7", label: "Dispatch support" },
      ],
    },
    settings: {
      title: "Settings",
      sub: "Manage your account, preferences and security.",
      profileTitle: "Profile",
      name: "Full name",
      company: "Company name",
      email: "Email address",
      phone: "Phone number",
      prefsTitle: "Preferences",
      language: "Language",
      notifTitle: "Notifications",
      notifShipment: "Shipment status updates",
      notifPayment: "Payment confirmations",
      notifDriver: "Driver check-in alerts",
      securityTitle: "Security",
      currentPw: "Current password",
      newPw: "New password",
      confirmPw: "Confirm new password",
      save: "Save changes",
      saved: "Saved",
      sessionTitle: "Session",
      sessionSub: "Sign out of CourierFlow on this device.",
      logout: "Sign out",
    },
    support: {
      title: "Need help?",
      call: "Call support",
      whatsapp: "Chat on WhatsApp",
    },
    shipmentsPage: {
      title: "Shipments",
      sub: "Every shipment moving across your network, in one place.",
      searchPlaceholder: "Search code, route, driver…",
      filterAll: "All",
      weight: "Weight",
      payer: "Billed to",
      empty: "No shipments match your filters.",
      showing: "Showing {n} of {total} shipments",
    },
    fleetPage: {
      title: "Fleet",
      sub: "Track every truck's status, driver and utilization.",
      searchPlaceholder: "Search truck, model, driver…",
      filterAll: "All",
      status_active: "Active",
      status_idle: "Idle",
      status_maintenance: "Maintenance",
      totalTrucks: "Total trucks",
      activeNow: "Active now",
      inMaintenance: "In maintenance",
      avgUtilization: "Avg. utilization",
      utilization: "Utilization",
      registerTruck: "Register truck",
      assignDriver: "Assign driver",
      assignTitle: "Assign driver to truck",
      selectDriver: "Driver",
      selectDriverPlaceholder: "Select a driver…",
      routeLabel: "Route",
      assignConfirm: "Assign",
      registerTitle: "Register new truck",
      truckId: "Truck ID",
      truckModel: "Model",
      truckCapacity: "Capacity",
      assignedDriver: "Assigned driver",
      noDriver: "Unassigned",
      registerConfirm: "Register",
      cancel: "Cancel",
    },
    driversPage: {
      title: "Drivers",
      sub: "Your roster, their routes and performance.",
      searchPlaceholder: "Search driver, truck…",
      filterAll: "All",
      status_route: "On route",
      status_available: "Available",
      status_off: "Off duty",
      trips: "trips this month",
      registerDriver: "Register driver",
      registerTitle: "Register new driver",
      driverName: "Full name",
      driverPhone: "Phone number",
      license: "License number",
      assignedTruck: "Assigned truck",
      noTruck: "Unassigned",
      registerConfirm: "Register",
      cancel: "Cancel",
    },
    trackingPage: {
      title: "Live tracking",
      sub: "Follow any shipment's exact route, in real time.",
      searchPlaceholder: "Search shipment…",
      stepLoading: "Loading",
      stepTransit: "In transit",
      stepDelivered: "Delivered",
      podTitle: "Proof of delivery",
      podSub: "Photo, signature and GPS stamp captured at handover.",
      viewInMap: "View in map",
    },
    reportsPage: {
      title: "Reports",
      sub: "Generate and print corporate-grade reports for your fleet operations.",
      shipmentsTitle: "Shipments Report",
      shipmentsSub: "All shipment activity, statuses and weights",
      paymentsTitle: "Payments Report",
      paymentsSub: "Mobile money transactions and settlement totals",
      fleetTitle: "Fleet Utilization Report",
      fleetSub: "Truck activity, efficiency and status breakdown",
      driversTitle: "Driver Performance Report",
      driversSub: "Driver roster, trips completed and ratings",
      generate: "Generate report",
      print: "Print report",
      officialReport: "Official Report",
      generatedOn: "Generated on",
      confidential: "Confidential — For internal use only",
      totalShipments: "Total shipments",
      delivered: "Delivered",
      delayed: "Delayed",
      collected: "Collected",
      pending: "Pending",
      transactions: "Transactions",
      totalTrucks: "Total trucks",
      activeTrucks: "Active",
      avgUtil: "Avg. utilization",
      totalDrivers: "Total drivers",
      onRoute: "On route",
      avgRating: "Avg. rating",
      truckId: "Truck ID",
      model: "Model",
      driver: "Driver",
      statusLabel: "Status",
      driverName: "Driver",
      contact: "Contact",
      assignedTruck: "Truck",
      tripsLabel: "Trips",
      ratingLabel: "Rating",
    },
    paymentsPage: {
      title: "Payments",
      sub: "Mobile money settlements across every shipment.",
      searchPlaceholder: "Search ID, code, payer…",
      filterAll: "All",
      collected: "Collected this month",
      pendingAmount: "Pending settlement",
      failedCount: "Failed transactions",
      avgValue: "Avg. transaction",
      id: "Transaction",
      payer: "Payer",
      method: "Method",
      status: "Status",
      date: "Date",
      amount: "Amount",
      status_paid: "Paid",
      status_pending: "Pending",
      status_failed: "Failed",
      method_mpesa: "M-Pesa",
      method_tigopesa: "Tigo Pesa",
      method_airtel: "Airtel Money",
    },
  },
  sw: {
    nav: {
      overview: "Muhtasari",
      shipments: "Mizigo",
      fleet: "Malori",
      drivers: "Madereva",
      tracking: "Ufuatiliaji",
      payments: "Malipo",
      reports: "Ripoti",
      settings: "Mipangilio",
      logout: "Toka",
    },
    profile: {
      name: "Amani Mwakalinga",
      email: "amani@highwaycargo.co.tz",
      settings: "Mipangilio ya akaunti",
      logout: "Toka",
    },
    overview: {
      greeting: "Karibu tena, Amani.",
      sub: "Hivi ndivyo malori yako yanavyosafiri leo.",
    },
    stats: {
      shipments: "Mizigo inayoendelea",
      trucks: "Malori barabarani",
      revenue: "Mapato mwezi huu",
      onTime: "Kiwango cha kuwasili kwa wakati",
    },
    table: {
      title: "Mizigo ya hivi karibuni",
      viewAll: "Ona yote",
      code: "Namba",
      route: "Njia",
      truck: "Lori na dereva",
      status: "Hali",
      eta: "Muda uliobaki",
      status_transit: "Safarini",
      status_delivered: "Imewasili",
      status_delayed: "Imechelewa",
      status_loading: "Inapakiwa",
    },
    map: {
      title: "Malori moja kwa moja",
      active: "njia zinazoendelea",
    },
    trust: {
      eyebrow: "Kwa nini malori yanaiamini CourierFlow",
      items: [
        { stat: "256-bit", label: "Malipo ya pesa za simu yaliyolindwa" },
        { stat: "97%", label: "Kiwango cha kuwasili kwa wakati" },
        { stat: "180+", label: "Malori kote Tanzania" },
        { stat: "24/7", label: "Msaada wa uendeshaji" },
      ],
    },
    settings: {
      title: "Mipangilio",
      sub: "Simamia akaunti yako, mapendeleo na usalama.",
      profileTitle: "Wasifu",
      name: "Jina kamili",
      company: "Jina la kampuni",
      email: "Barua pepe",
      phone: "Namba ya simu",
      prefsTitle: "Mapendeleo",
      language: "Lugha",
      notifTitle: "Arifa",
      notifShipment: "Arifa za hali ya mzigo",
      notifPayment: "Uthibitisho wa malipo",
      notifDriver: "Arifa za madereva",
      securityTitle: "Usalama",
      currentPw: "Nenosiri la sasa",
      newPw: "Nenosiri jipya",
      confirmPw: "Thibitisha nenosiri jipya",
      save: "Hifadhi mabadiliko",
      saved: "Imehifadhiwa",
      sessionTitle: "Kipindi",
      sessionSub: "Toka kwenye CourierFlow kwenye kifaa hiki.",
      logout: "Toka",
    },
    support: {
      title: "Unahitaji msaada?",
      call: "Piga simu kwa msaada",
      whatsapp: "Ongea kwa WhatsApp",
    },
    shipmentsPage: {
      title: "Mizigo",
      sub: "Mizigo yote inayosafiri kwenye mtandao wako, mahali pamoja.",
      searchPlaceholder: "Tafuta namba, njia, dereva…",
      filterAll: "Yote",
      weight: "Uzito",
      payer: "Anayelipa",
      empty: "Hakuna mzigo unaolingana na uchujaji wako.",
      showing: "Inaonyesha mizigo {n} kati ya {total}",
    },
    fleetPage: {
      title: "Malori",
      sub: "Fuatilia hali, dereva na matumizi ya kila lori.",
      searchPlaceholder: "Tafuta lori, aina, dereva…",
      filterAll: "Yote",
      status_active: "Linafanya kazi",
      status_idle: "Halipo kazini",
      status_maintenance: "Matengenezo",
      totalTrucks: "Jumla ya malori",
      activeNow: "Yanayofanya kazi sasa",
      inMaintenance: "Kwenye matengenezo",
      avgUtilization: "Wastani wa matumizi",
      utilization: "Matumizi",
      registerTruck: "Sajili lori",
      assignDriver: "Gawa dereva",
      assignTitle: "Gawa dereva kwenye lori",
      selectDriver: "Dereva",
      selectDriverPlaceholder: "Chagua dereva…",
      routeLabel: "Njia",
      assignConfirm: "Gawa",
      registerTitle: "Sajili lori jipya",
      truckId: "Namba ya lori",
      truckModel: "Aina",
      truckCapacity: "Uzito wa kubeba",
      assignedDriver: "Dereva aliyegawiwa",
      noDriver: "Bila dereva",
      registerConfirm: "Sajili",
      cancel: "Ghairi",
    },
    driversPage: {
      title: "Madereva",
      sub: "Orodha ya madereva, njia zao na utendaji.",
      searchPlaceholder: "Tafuta dereva, lori…",
      filterAll: "Yote",
      status_route: "Safarini",
      status_available: "Yupo tayari",
      status_off: "Hayupo kazini",
      trips: "safari mwezi huu",
      registerDriver: "Sajili dereva",
      registerTitle: "Sajili dereva mpya",
      driverName: "Jina kamili",
      driverPhone: "Namba ya simu",
      license: "Namba ya leseni",
      assignedTruck: "Lori alilonalo",
      noTruck: "Bila lori",
      registerConfirm: "Sajili",
      cancel: "Ghairi",
    },
    trackingPage: {
      title: "Ufuatiliaji wa moja kwa moja",
      sub: "Fuatilia njia kamili ya mzigo wowote, kwa wakati halisi.",
      searchPlaceholder: "Tafuta mzigo…",
      stepLoading: "Inapakiwa",
      stepTransit: "Safarini",
      stepDelivered: "Imewasili",
      podTitle: "Uthibitisho wa uwasilishaji",
      podSub: "Picha, sahihi na alama ya GPS zilizopigwa wakati wa kukabidhi.",
      viewInMap: "Tazama ramani",
    },
    reportsPage: {
      title: "Ripoti",
      sub: "Tengeneza na chapisha ripoti za kikampuni kwa ajili ya malori yako.",
      shipmentsTitle: "Ripoti ya Mizigo",
      shipmentsSub: "Shughuli zote za mizigo, hali na uzito",
      paymentsTitle: "Ripoti ya Malipo",
      paymentsSub: "Miamala ya pesa za simu na jumla ya makusanyo",
      fleetTitle: "Ripoti ya Matumizi ya Malori",
      fleetSub: "Shughuli, ufanisi na hali ya malori",
      driversTitle: "Ripoti ya Utendaji wa Madereva",
      driversSub: "Orodha ya madereva, safari zilizokamilika na viwango",
      generate: "Tengeneza ripoti",
      print: "Chapisha ripoti",
      officialReport: "Ripoti Rasmi",
      generatedOn: "Imetengenezwa tarehe",
      confidential: "Siri — Kwa matumizi ya ndani pekee",
      totalShipments: "Jumla ya mizigo",
      delivered: "Iliyowasili",
      delayed: "Iliyochelewa",
      collected: "Yaliyokusanywa",
      pending: "Yanayosubiri",
      transactions: "Miamala",
      totalTrucks: "Jumla ya malori",
      activeTrucks: "Yanayofanya kazi",
      avgUtil: "Wastani wa matumizi",
      totalDrivers: "Jumla ya madereva",
      onRoute: "Safarini",
      avgRating: "Kiwango cha wastani",
      truckId: "Namba ya lori",
      model: "Aina",
      driver: "Dereva",
      statusLabel: "Hali",
      driverName: "Dereva",
      contact: "Mawasiliano",
      assignedTruck: "Lori",
      tripsLabel: "Safari",
      ratingLabel: "Kiwango",
    },
    paymentsPage: {
      title: "Malipo",
      sub: "Malipo ya pesa za simu kwa kila mzigo.",
      searchPlaceholder: "Tafuta namba, mzigo, mlipaji…",
      filterAll: "Yote",
      collected: "Yaliyokusanywa mwezi huu",
      pendingAmount: "Yanayosubiri kuthibitishwa",
      failedCount: "Malipo yaliyoshindwa",
      avgValue: "Wastani wa muamala",
      id: "Muamala",
      payer: "Mlipaji",
      method: "Njia",
      status: "Hali",
      date: "Tarehe",
      amount: "Kiasi",
      status_paid: "Imelipwa",
      status_pending: "Inasubiri",
      status_failed: "Imeshindwa",
      method_mpesa: "M-Pesa",
      method_tigopesa: "Tigo Pesa",
      method_airtel: "Airtel Money",
    },
  },
};
